server:
    port:
spring:
    datasource:
        url:
        username:
        password:
        driver-class-name:
    jpa:
        properties:
            hibernate:
                dialect:
        hibernate:
            ddl-auto:
    flyway:
        url:
        user:
        password:
        enabled:
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri:
                    issuer-uri:
app:
    properties:
        security:
            enable:
        keycloak:
            CLIENT_SECRET:
            ADMIN_USERNAME:
            ADMIN_PASSWORD:
